<a href="https://colab.research.google.com/github/mounaky/ML_2023/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy 

import numpy as np

In [ ]:
#create numpy array or nd arrays

arr = np.array([1,2,3,4]) #np
print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#0- D array
arr1 = np.array(24)
print(arr1)

print(arr1.ndim)

print('dimension: ',arr1.ndim)
print('shape: ',arr1.shape)

24
0
dimension:  0
shape:  ()


In [ ]:
#1-D array : to create a 1D array specify a layer of square brackets

arr1=np.array([2,3,4]) #1 item
print(arr1)

print(arr1.ndim)

print('dimension: ',arr1.ndim)
print('shape: ',arr1.shape)


[2 3 4]
1
dimension:  1
shape:  (3,)


In [ ]:
#2-D array : 
arr1=np.array([[2,3,4],[3,4,5]])   #1 item
print(arr1)

print(arr1.ndim)

print('dimension: ',arr1.ndim)
print('shape: ',arr1.shape)          #shape =(2) rows and (3)col..


[[2 3 4]
 [3 4 5]]
2
dimension:  2
shape:  (2, 3)


In [ ]:
#craete 2D array whose shape =(3,3)

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

print('dimension: ',arr1.ndim)
print('shape: ',arr1.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension:  2
shape:  (3, 3)


In [ ]:
import numpy as np

arr1=np.array([1,2,3])
print(arr1)

print('dimension : ',arr1.ndim)
print('shape: ',arr1.shape)

[1 2 3]
dimension :  1
shape:  (3,)


In [ ]:
#craete 2D array whose shape =(4,3)
arr2=np.array([[1,2,3],[1,2,3],[3,4,5],[5,6,7]])
print(arr2)
print('dimension :',arr2.ndim)
print('shape:' ,arr2.shape)


[[1 2 3]
 [1 2 3]
 [3 4 5]
 [5 6 7]]
dimension : 2
shape: (4, 3)


In [ ]:
#craete 3D array whose shape 
arr3=np.array([[[2,3,4],[5,6,7],[5,6,7],[3,4,5]],[[2,3,4],[5,6,7],[5,6,7],[3,4,5]]])
print(arr3)
print('dimension: ',arr3.ndim)
print('shape: ', arr3.shape)                    #shape=(2,4,3) 2-no of blocks in array

[[[2 3 4]
  [5 6 7]
  [5 6 7]
  [3 4 5]]

 [[2 3 4]
  [5 6 7]
  [5 6 7]
  [3 4 5]]]
dimension:  3
shape:  (2, 4, 3)


In [ ]:
#craete 4D array whose shape 
arr4=np.array([[[[2,3,4],[5,6,7],[6,7,8],[2,3,4]]]])
print(arr4)

print('dimension: ',arr4.ndim)  #print(arr4.ndim)
print('shape: ',arr4.shape)

[[[[2 3 4]
   [5 6 7]
   [6 7 8]
   [2 3 4]]]]
dimension:  4
shape:  (1, 1, 4, 3)


0-Darray 0 square brackets
1-d 1 square brack..
2-d 2 sqaure brack.         #(start and end)
3-d 3 square brack..

In [ ]:
arr1 = np.array([1,2,3,4] , ndim=2)
print(arr1)

[[1 2 3 4]]


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=arr1+arr2
print(arr3)

[ 6  8 10 12]


In [ ]:
arr1=np.array([[1,2,3,4],[1,5,8,9]])
arr2=np.array([5,6,7,8])
arr3=arr1+arr2
print(arr3)

[[ 6  8 10 12]
 [ 6 11 15 17]]


In [ ]:
arr1=np.array([[1,2,3,4],[1,5,8,9]])
arr2=np.array([[5,6,7,8],[5,7,9,6]])
arr3=arr1+arr2
print(arr3)

[[ 6  8 10 12]
 [ 6 12 17 15]]


In [ ]:
#prg to create sum of all the items in 1D array

arr1=np.array([1,2,3,4])
sum=0
for i in arr1:
  sum+=i
print(sum)

10


In [ ]:
#accessing elements of 2D array

arr1=np.array([[1,2,3],[3,4,5]])
print(arr1[1][-2])
print(arr1[1,1:3])
print(arr1[0:2,0:2])

4
[4 5]
[[1 2]
 [3 4]]


In [ ]:
#accessing 3D array

arr3=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])    #shape (2,2,3) 2-dimension, 2- how many blocks are there in in [], 3-elements in array
print(arr3)
print('shape: ',arr3.shape)
print(arr3[1][1][2])
print(arr3[0,1,0:2])
print(arr3[1,0,1])
print(arr3[0:2,1:2,0:2])

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
shape:  (2, 2, 3)
9
[3 4]
6
[[[3 4]]

 [[7 8]]]


In [ ]:
#print scalar values or 0-d array elements
arr1 = np.array([[1,2,3],[4,5,6]])

for x in arr1:
  for y in x:  # to order in array in one by one in line 
    print(y,end=' ')

1 2 3 4 5 6 

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#print scalar values or 0-d array elements of 3d numpy array

arr1 = np.array([[[1,2,3],[3,4,5],[4,5,6]]])
print('shape: ',arr1.shape)
for x in arr1:
  for y in x:
    for i in y:
     print(i,end=' ')
     #print('shape: ',arr1.shape)

shape:  (1, 3, 3)
1 2 3 3 4 5 4 5 6 

In [ ]:
#nditer()
arr1 = np.array([[[1,2,3],[3,4,5],[4,5,6]],[[7,78,9],[6,7,8],[9,0,4]]])
for x in np.nditer(arr1):  # iteration
  print(x,end=' ')

1 2 3 3 4 5 4 5 6 7 78 9 6 7 8 9 0 4 

In [ ]:
#populate arrays with sequence of numbers: 
#arange()

arr1=np.arange(5,12)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[ 5  6  7  8  9 10 11]
1
(7,)


In [ ]:
arr1=np.arange(5,12,2) # 2 skips(add)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[ 5  7  9 11]
1
(4,)


In [ ]:
#pop[ulate array with random numbers
#np.random.randint(low,high,size)

arr1 = np.random.randint(low=10, high=20,size=(7))
print(arr1)



[17 10 12 17 19 14 13]


In [ ]:
arr1 = np.random.randint(low=10, high=20,size=(5,2,3)) #rows and col
print(arr1)

[[[10 16 13]
  [18 17 13]]

 [[13 17 17]
  [15 18 12]]

 [[16 17 14]
  [10 10 12]]

 [[18 10 11]
  [17 12 11]]

 [[18 19 19]
  [11 13 13]]]


In [ ]:
#broadcasting : 
#2=[[2,2,2],[2,2,2]]=arr1
arr1 = np.array([[2,3,4],[4,5,6]]) # it add 2 for every elements
print(arr1 + 2)
print(arr1*2)

[[4 5 6]
 [6 7 8]]
[[ 4  6  8]
 [ 8 10 12]]


In [ ]:
#create a linear dataset
#create a simple dataset consisiting of a single feature and a label as follows:
#1. assign a sequence of integers frm 6 to 20(inclucive) to a numpy array named faeture
#2.assign 15 values to numpy array named label such that

#label = (3)(faeture) +a
# for example the first value for label should be:
#label =(3)(6) + 4 =22

feature = np.arange(6,21)
label =3*feature+4
print(feature)
print(label)


[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
